version: "3.3"
services:
  mongodb:
    image: mongo:3.5
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  web:
    image: branchzero/yapi:latest
    command: /bin/bash -c "[ ! -e /home/yapi/log/init.lock ] && npm run install-server && touch /home/yapi/log/init.lock; npm run start"
    links:
      - mongodb:mongodb
    ports:
      - 3000:3000
    volumes:
      - ./config.json:/home/yapi/config.json
      - ./data/yapi:/home/yapi/log